### DISCUSSION TITLE
Allow template shortcuts to session

### DISCUSSION THREAD

**Discussion by DonnC** [DonnC/jawce#19] [Ideas]
It would be nice to allow a template to quickly access session data without using a template hook

For example 

```yaml
"GET_USER_NAME":
  type: text
  prop: username
  message: "Provide your name"
  routes:
    "re:\\s+": "CONFIRM_NAME"

"CONFIRM_NAME":
  type: text
  message: "Confirm that your username is {{ p.username }}"
  routes:
    "re:.*": "next-stage"
```

Where `p` reference a prop data and `s` can reference a normal session data
